import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string, replacements?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<string, Record<string, string>> = {
  en: {
    home: 'Home',
    routes: 'Routes',
    booking: 'Booking',
    about: 'About',
    contact: 'Contact',
    signIn: 'Sign in',
    blog: 'Blog',
    kimsengExpress: 'Kimseng Express',
    english: 'English',
    khmer: 'ខ្មែរ',
    language: 'Language',
    // Index Page
    discoverYourWorld: 'Discover Your World',
    discoverAmazingPlaces: 'Discover amazing places at exclusive deals',
    trustedPartners: 'Trusted Partners',
    leadingOrganizations: 'We work with leading organizations to ensure quality service',
    tourismCambodia: 'Tourism Cambodia',
    transportMinistry: 'Transport Ministry',
    safetyFirst: 'Safety First',
    travelSafe: 'Travel Safe',
    greenTravel: 'Green Travel',
    customerChoice: 'Customer Choice',
    downloadMobileApp: 'Download Our Mobile App',
    bookTicketsTrackJourney: 'Book tickets, track your journey, and manage your trips on the go',
    downloadForAndroid: 'Download for Android',
    downloadForIOS: 'Download for iOS',
    easyBooking: 'Easy Booking',
    bookTicketsInFewTaps: 'Book your tickets in just a few taps',
    realtimeTracking: 'Real-time Tracking',
    trackBusLocation: 'Track your bus location and arrival time',
    digitalTickets: 'Digital Tickets',
    noPaperTickets: 'No need for paper tickets - go digital',
    topDestinations: 'Top Destinations',
    popularDestinationsOffer: 'These popular destinations has lot of to offer',
    phnomPenhDescription: 'The capital city, known for its rich history and royal palace.',
    kampotDescription: 'A charming riverside town famous for its pepper plantations and natural beauty.',
    kepDescription: 'A tranquil coastal province, once a French colonial resort town, now known for its fresh seafood and serene beaches.',
    mondulkiriDescription: 'A northeastern province characterized by its lush forests, waterfalls, and elephant sanctuaries.',
    selectSeats: 'Select Seats',
    // Hero Page
    discoverYourCambodia: 'Discover Your Cambodia',
    safeReliableComfortable: 'Safe, reliable, and comfortable travel across Cambodia',
    from: 'From',
    departureLocation: 'Departure Location',
    to: 'To',
    destinationLocation: 'Destination Location',
    departure: 'Departure',
    selectDate: 'Select date',
    passengers: 'Passengers',
    passenger: 'Passenger',
    passengersPlural: 'Passengers',
    search: 'Search',
    viewAllRoutes: 'View All Routes',
    bookNow: 'Book Now',
    fillAllFields: 'Please fill in all required fields',
    siemReap: 'Siem Reap',
    battambang: 'Battambang',
    sihanoukville: 'Sihanoukville',
    phnomPenh: 'Phnom Penh',
    kampot: 'Kampot',
    kep: 'Kep',
    mondulkiri: 'Mondulkiri',
    // Routes Page
    ourRoutes: 'Our Routes',
    reliableTransportation: 'Reliable transportation to your favorite destinations',
    arrival: 'Arrival',
    duration: 'Duration',
    frequency: 'Frequency',
    // Booking Page
    bookYourJourney: 'Book Your Journey',
    reserveYourSeat: 'Reserve your seat for a comfortable trip',
    bookingDetails: 'Booking Details',
    selectDepartureCity: 'Select departure city',
    selectDestinationCity: 'Select destination city',
    departureTime: 'Departure Time',
    selectTime: 'Select time',
    passengerInformation: 'Passenger Information',
    firstName: 'First Name',
    enterFirstName: 'Enter first name',
    lastName: 'Last Name',
    enterLastName: 'Enter last name',
    email: 'Email',
    enterEmailAddress: 'Enter email address',
    phoneNumber: 'Phone Number',
    enterPhoneNumber: 'Enter phone number',
    specialRequests: 'Special Requests',
    anySpecialRequests: 'Any special requests or notes?',
    confirmBooking: 'Confirm Booking',
    maxSeatsReached: 'You can only select {num} seats.',
    warning: 'Warning',
    seatAlreadySelected: 'This seat is already selected by another passenger.',
    maxPassengersReached: 'You have reached the maximum number of passengers ({num}).',
    selectAtLeastOneSeat: 'Please select at least one seat for each passenger.',
    fillAllRequiredFields: 'Please fill in all required fields.',
    bookingFailed: 'Booking failed. Please try again.',
    bookingSuccess: 'Booking successful!',
    checkEmailForConfirmation: 'Check your email for confirmation.',
    error: 'Error',
    invalidInput: 'Invalid input. Please check your details.',
    somethingWentWrong: 'Something went wrong. Please try again later.',
    connectionError: 'Connection error. Please check your internet connection.',
    seatSelectionError: 'Seat selection error. Please try again.',
    // Contact Page
    contactUs: 'Contact Us',
    getInTouch: 'Get in touch with our friendly team',
    phone: 'Phone',
    mainOffice: 'Main Office',
    officeHours: 'Office Hours',
    mondayFriday: 'Monday - Friday:',
    saturday: 'Saturday:',
    sunday: 'Sunday:',
    sendMessage: 'Send us a message',
    john: 'John',
    doe: 'Doe',
    generalInquiry: 'General Inquiry',
    bookingSupport: 'Booking Support',
    complaint: 'Complaint',
    suggestion: 'Suggestion',
    howCanWeHelp: 'How can we help you?',
    sendMessageButton: 'Send Message',
    ourLocation: 'Our Location',
    googleMapsIntegration: 'Google Maps integration would be implemented here',
    mainOfficeAddress: 'Main Office: 123 Street 271, Toul Kork, Phnom Penh',
    thankYouMessage: 'Thank you for your message! We will get back to you soon.',
    // Login Page
    welcomeBack: 'Welcome Back',
    signInToYourAccount: 'Sign in to your account',
    password: 'Password',
    enterYourEmail: 'Enter your email',
    enterYourPassword: 'Enter your password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    loginFunctionality: 'Login functionality would be implemented with authentication system',
    dontHaveAccount: 'Don\'t have an account?',
    signUpHere: 'Sign up here',
    // Signup Page
    createAccount: 'Create Account',
    joinKimsengExpress: 'Join Kimseng Express today',
    confirmPassword: 'Confirm Password',
    createAPassword: 'Create a password',
    confirmYourPassword: 'Confirm your password',
    passwordsDoNotMatch: 'Passwords do not match',
    iAgreeToThe: 'I agree to the',
    termsOfService: 'Terms of Service',
    and: 'and',
    privacyPolicy: 'Privacy Policy',
    alreadyHaveAccount: 'Already have an account?',
    // About Page
    aboutKimsengExpress: 'About Kimseng Express',
    trustedTravelPartner: 'Your trusted travel partner in Cambodia',
    ourMission: 'Our Mission',
    missionStatementPart1: 'At Kimseng Express, we are committed to providing safe, reliable, and comfortable transportation services across Cambodia. Since our establishment, we have been connecting people to their destinations with a focus on punctuality, safety, and customer satisfaction.',
    missionStatementPart2: 'We believe that travel should be stress-free and enjoyable. That\'s why we maintain the highest standards in vehicle maintenance, driver training, and customer service to ensure every journey with us is a positive experience.',
    ourAchievements: 'Our Achievements',
    happyCustomers: 'Happy Customers',
    yearsExperience: 'Years Experience',
    routesCovered: 'Routes Covered',
    onTimeArrival: 'On-Time Arrival',
    linterWarnings: 'Linter warnings and errors.',
    ourVehicleFleet: 'Our Vehicle Fleet',
    standardBus: 'Standard Bus',
    capacity: 'Capacity',
    passengersShort: 'passengers',
    airConditioning: 'Air Conditioning',
    comfortableSeats: 'Comfortable Seats',
    storageSpace: 'Storage Space',
    vipBus: 'VIP Bus',
    recliningSeats: 'Reclining Seats',
    extraLegroom: 'Extra Legroom',
    entertainmentSystem: 'Entertainment System',
    miniVan: 'Mini Van',
    privateTransport: 'Private Transport',
    flexibleSchedule: 'Flexible Schedule',
    doorToDoorService: 'Door-to-Door Service',
    safetyStandards: 'Safety Standards',
    yourSafetyPriority: 'Your safety is our top priority. We maintain the highest safety standards in everything we do.',
    vehicleSafety: 'Vehicle Safety',
    regularVehicleMaintenance: 'Regular vehicle maintenance and inspections',
    modernSafetyEquipment: 'Modern safety equipment and emergency exits',
    gpsTracking: 'GPS tracking and communication systems',
    firstAidKits: 'First aid kits and safety equipment onboard',
    driverTraining: 'Driver Training',
    professionalDriverCertification: 'Professional driver certification and training',
    regularSafetyTraining: 'Regular safety and customer service training',
    backgroundChecks: 'Background checks and health examinations',
    continuousMonitoring: 'Continuous monitoring and performance evaluation',
    // Booking Confirmation Page
    noBookingDataFound: 'No booking data found',
    makeABooking: 'Make a Booking',
    bookingConfirmed: 'Booking Confirmed!',
    bookingSuccessfullySubmitted: 'Your booking has been successfully submitted',
    bookingID: 'Booking ID:',
    tripInformation: 'Trip Information',
    route: 'Route',
    departureDate: 'Departure Date',
    totalPassengers: 'Total Passengers',
    passengerDetails: 'Passenger Details',
    primaryPassenger: 'Primary Passenger',
    importantInformation: 'Important Information',
    arriveEarly: 'Please arrive at the departure location 30 minutes before scheduled time',
    validID: 'Bring a valid ID for verification',
    contactForChanges: 'Contact us at +855 69 373 415 if you need to make changes',
    confirmationEmailSent: 'A confirmation email will be sent to',
    backToHome: 'Back to Home',
    makeAnotherBooking: 'Make Another Booking',
    dateNotSelected: 'Date not selected',
    notFound_oops: "Oops! Page not found",
    notFound_returnHome: "Return to Home",
    availableTrips: "Available Trips",
    arrivalTime: "Arrival Time",
    vanType: "Van Type",
    findTrips: "Find Trips",
    viewBookingHistory: 'My Bookings',
  },
  km: {
    home: 'ទំព័រដើម',
    routes: 'ផ្លូវ',
    booking: 'កក់',
    about: 'អំពី',
    contact: 'ទំនាក់ទំនង',
    signIn: 'ចូល',
    blog: 'ប្លុក',
    kimsengExpress: 'គីមសេង អ៊ិចប្រេស',
    english: 'អង់គ្លេស',
    khmer: 'ខ្មែរ',
    language: 'ភាសា',
    // Index Page
    discoverYourWorld: 'ស្វែងយល់ពីពិភពលោករបស់អ្នក',
    discoverAmazingPlaces: 'ស្វែងយល់ពីកន្លែងអស្ចារ្យជាមួយនឹងការបញ្ចុះតម្លៃពិសេស',
    trustedPartners: 'ដៃគូដែលទុកចិត្ត',
    leadingOrganizations: 'យើងធ្វើការជាមួយអង្គការឈានមុខគេដើម្បីធានាសេវាកម្មប្រកបដោយគុណភាព',
    tourismCambodia: 'ទេសចរណ៍កម្ពុជា',
    transportMinistry: 'ក្រសួងដឹកជញ្ជូន',
    safetyFirst: 'សុវត្ថិភាពដំបូង',
    travelSafe: 'ធ្វើដំណើរដោយសុវត្ថិភាព',
    greenTravel: 'ការធ្វើដំណើរបៃតង',
    customerChoice: 'ជម្រើសអតិថិជន',
    downloadMobileApp: 'ទាញយកកម្មវិធីទូរស័ព្ទរបស់យើង',
    bookTicketsTrackJourney: 'កក់សំបុត្រ តាមដានការធ្វើដំណើរ និងគ្រប់គ្រងការធ្វើដំណើររបស់អ្នកនៅពេលធ្វើដំណើរ',
    downloadForAndroid: 'ទាញយកសម្រាប់ Android',
    downloadForIOS: 'ទាញយកសម្រាប់ iOS',
    easyBooking: 'ការកក់ងាយស្រួល',
    bookTicketsInFewTaps: 'កក់សំបុត្ររបស់អ្នកដោយគ្រាន់តែចុចពីរបីដង',
    realtimeTracking: 'ការតាមដានពេលវេលាពិត',
    trackBusLocation: 'តាមដានទីតាំងឡានក្រុង និងពេលវេលាមកដល់របស់អ្នក',
    digitalTickets: 'សំបុត្រឌីជីថល',
    noPaperTickets: 'មិនចាំបាច់មានសំបុត្រក្រដាសទេ - ប្រើឌីជីថល',
    topDestinations: 'គោលដៅកំពូល',
    popularDestinationsOffer: 'គោលដៅពេញនិយមទាំងនេះមានច្រើនដើម្បីផ្តល់ជូន',
    phnomPenhDescription: 'រាជធានីល្បីល្បាញដោយសារប្រវត្តិសាស្រ្ត និងព្រះបរមរាជវាំងដ៏សម្បូរបែប.',
    kampotDescription: 'ទីក្រុងមាត់ទន្លេដ៏ស្រស់ស្អាត ល្បីល្បាញដោយសារចំការម្រេច និងសម្រស់ធម្មជាតិ.',
    kepDescription: 'ខេត្តឆ្នេរសមុទ្រដ៏ស្ងប់ស្ងាត់ ធ្លាប់ជាទីក្រុងរមណីយដ្ឋានអាណានិគមបារាំង បច្ចុប្បន្នល្បីល្បាញដោយសារអាហារសមុទ្រស្រស់ៗ និងឆ្នេរខ្សាច់ស្ងប់ស្ងាត់.',
    mondulkiriDescription: 'ខេត្តភាគឦសានដែលមានលក្ខណៈជាព្រៃឈើខៀវស្រងាត់ ទឹកជ្រោះ និងជម្រកដំរី.',
    selectSeats: 'ជ្រើសរើសកៅអី',
    // Hero Page
    discoverYourCambodia: 'ស្វែងយល់ពីប្រទេសកម្ពុជារបស់អ្នក',
    safeReliableComfortable: 'ការធ្វើដំណើរប្រកបដោយសុវត្ថិភាព អាចទុកចិត្តបាន និងផាសុកភាពទូទាំងប្រទេសកម្ពុជា',
    from: 'ពី',
    departureLocation: 'ទីតាំងចេញដំណើរ',
    to: 'ទៅ',
    destinationLocation: 'ទីតាំងគោលដៅ',
    departure: 'ចេញដំណើរ',
    selectDate: 'ជ្រើសរើសកាលបរិច្ឆេទ',
    passengers: 'អ្នកដំណើរ',
    passenger: 'អ្នកដំណើរ',
    passengersPlural: 'អ្នកដំណើរ',
    search: 'ស្វែងរក',
    viewAllRoutes: 'មើលផ្លូវទាំងអស់',
    bookNow: 'កក់ឥឡូវ',
    fillAllFields: 'សូមបំពេញគ្រប់វាលដែលត្រូវការ',
    siemReap: 'សៀមរាប',
    battambang: 'បាត់ដំបង',
    sihanoukville: 'ព្រះសីហនុ',
    phnomPenh: 'ភ្នំពេញ',
    kampot: 'កំពត',
    kep: 'កែប',
    mondulkiri: 'មណ្ឌលគិរី',
    // Routes Page
    ourRoutes: 'ផ្លូវរបស់យើង',
    reliableTransportation: 'ការដឹកជញ្ជូនដែលអាចទុកចិត្តបានទៅកាន់គោលដៅដែលអ្នកចូលចិត្ត',
    arrival: 'មកដល់',
    duration: 'រយៈពេល',
    frequency: 'ប្រេកង់',
    // Booking Page
    bookYourJourney: 'កក់ការធ្វើដំណើររបស់អ្នក',
    reserveYourSeat: 'កក់កៅអីរបស់អ្នកសម្រាប់ការធ្វើដំណើរប្រកបដោយផាសុកភាព',
    bookingDetails: 'ព័ត៌មានលម្អិតនៃការកក់',
    selectDepartureCity: 'ជ្រើសរើសទីក្រុងចេញដំណើរ',
    selectDestinationCity: 'ជ្រើសរើសទីក្រុងគោលដៅ',
    departureTime: 'ម៉ោងចេញដំណើរ',
    selectTime: 'ជ្រើសរើសពេលវេលា',
    passengerInformation: 'ព័ត៌មានអ្នកដំណើរ',
    firstName: 'នាមខ្លួន',
    enterFirstName: 'បញ្ចូលនាមខ្លួន',
    lastName: 'នាមត្រកូល',
    enterLastName: 'បញ្ចូលនាមត្រកូល',
    email: 'អ៊ីមែល',
    enterEmailAddress: 'បញ្ចូលអាសយដ្ឋានអ៊ីមែល',
    phoneNumber: 'លេខទូរស័ព្ទ',
    enterPhoneNumber: 'បញ្ចូលលេខទូរស័ព្ទ',
    specialRequests: 'សំណើពិសេស',
    anySpecialRequests: 'មានសំណើពិសេស ឬកំណត់ចំណាំទេ?',
    confirmBooking: 'បញ្ជាក់ការកក់',
    maxSeatsReached: 'អ្នកអាចជ្រើសរើសបានតែ {num} កៅអីប៉ុណ្ណោះ។',
    warning: 'ការព្រមាន',
    seatAlreadySelected: 'កៅអីនេះត្រូវបានជ្រើសរើសដោយអ្នកដំណើរផ្សេងទៀត។',
    maxPassengersReached: 'អ្នកបានដល់ចំនួនអ្នកដំណើរអតិបរមា ({num}) ហើយ។',
    selectAtLeastOneSeat: 'សូមជ្រើសរើសយ៉ាងហោចណាស់មួយកៅអីសម្រាប់អ្នកដំណើរម្នាក់ៗ។',
    fillAllRequiredFields: 'សូមបំពេញគ្រប់វាលដែលតម្រូវ។',
    bookingFailed: 'ការកក់បានបរាជ័យ។ សូមព្យាយាមម្តងទៀត។',
    bookingSuccess: 'ការកក់បានជោគជ័យ!',
    checkEmailForConfirmation: 'សូមពិនិត្យមើលអ៊ីមែលរបស់អ្នកសម្រាប់ការបញ្ជាក់។',
    error: 'កំហុស',
    invalidInput: 'ការបញ្ចូលមិនត្រឹមត្រូវ។ សូមពិនិត្យមើលព័ត៌មានលម្អិតរបស់អ្នក។',
    somethingWentWrong: 'មានអ្វីមួយខុសប្រក្រតី។ សូមព្យាយាមម្តងទៀតនៅពេលក្រោយ។',
    connectionError: 'កំហុសក្នុងការតភ្ជាប់។ សូមពិនិត្យមើលការតភ្ជាប់អ៊ីធឺណិតរបស់អ្នក។',
    seatSelectionError: 'កំហុសក្នុងការជ្រើសរើសកៅអី។ សូមព្យាយាមម្តងទៀត។',
    // Contact Page
    contactUs: 'ទំនាក់ទំនងយើង',
    getInTouch: 'ទាក់ទងក្រុមការងាររបស់យើង',
    phone: 'ទូរស័ព្ទ',
    mainOffice: 'ការិយាល័យកណ្តាល',
    officeHours: 'ម៉ោងការិយាល័យ',
    mondayFriday: 'ច័ន្ទ - សុក្រ:',
    saturday: 'សៅរ៍:',
    sunday: 'អាទិត្យ:',
    sendMessage: 'ផ្ញើសារមកយើង',
    john: 'ចន',
    doe: 'ដូ',
    generalInquiry: 'ការសាកសួរបូកសរុប',
    bookingSupport: 'ជំនួយការកក់',
    complaint: 'បណ្តឹង',
    suggestion: 'សំណូមពរ',
    howCanWeHelp: 'តើយើងអាចជួយអ្នកដោយរបៀបណា?',
    sendMessageButton: 'ផ្ញើសារ',
    ourLocation: 'ទីតាំងរបស់យើង',
    googleMapsIntegration: 'ការរួមបញ្ចូល Google Maps នឹងត្រូវបានអនុវត្តនៅទីនេះ',
    mainOfficeAddress: 'ការិយាល័យកណ្តាល: ផ្លូវ 123 271, ទួលគោក, ភ្នំពេញ',
    thankYouMessage: 'អរគុណសម្រាប់សាររបស់អ្នក! យើងនឹងទាក់ទងទៅអ្នកឆាប់ៗ',
    // Login Page
    welcomeBack: 'សូមស្វាគមន៍',
    signInToYourAccount: 'ចូលគណនីរបស់អ្នក',
    password: 'ពាក្យសម្ងាត់',
    enterYourEmail: 'បញ្ចូលអ៊ីមែលរបស់អ្នក',
    enterYourPassword: 'បញ្ចូលពាក្យសម្ងាត់របស់អ្នក',
    rememberMe: 'ចងចាំខ្ញុំ',
    forgotPassword: 'ភ្លេចពាក្យសម្ងាត់?',
    loginFunctionality: 'មុខងារចូលនឹងត្រូវបានអនុវត្តជាមួយនឹងប្រព័ន្ធផ្ទៀងផ្ទាត់',
    dontHaveAccount: 'មិនមានគណនី?',
    signUpHere: 'ចុះឈ្មោះនៅទីនេះ',
    // Signup Page
    createAccount: 'បង្កើតគណនី',
    joinKimsengExpress: 'ចូលរួមជាមួយគីមសេង អ៊ិចប្រេស ថ្ងៃនេះ',
    confirmPassword: 'បញ្ជាក់ពាក្យសម្ងាត់',
    createAPassword: 'បង្កើតពាក្យសម្ងាត់',
    confirmYourPassword: 'បញ្ជាក់ពាក្យសម្ងាត់របស់អ្នក',
    passwordsDoNotMatch: 'ពាក្យសម្ងាត់មិនត្រូវគ្នា',
    iAgreeToThe: 'ខ្ញុំយល់ព្រមនឹង',
    termsOfService: 'លក្ខខណ្ឌប្រើប្រាស់',
    and: 'និង',
    privacyPolicy: 'គោលការណ៍ឯកជនភាព',
    alreadyHaveAccount: 'មានគណនីរួចហើយ?',
    // About Page
    aboutKimsengExpress: 'អំពីគីមសេង អ៊ិចប្រេស',
    trustedTravelPartner: 'ដៃគូធ្វើដំណើរដែលអ្នកទុកចិត្តនៅកម្ពុជា',
    ourMission: 'បេសកកម្មរបស់យើង',
    missionStatementPart1: 'នៅគីមសេង អ៊ិចប្រេស យើងប្តេជ្ញាផ្តល់សេវាកម្មដឹកជញ្ជូនប្រកបដោយសុវត្ថិភាព អាចទុកចិត្តបាន និងផាសុកភាពទូទាំងប្រទេសកម្ពុជា។ ចាប់តាំងពីការបង្កើតឡើង យើងបានភ្ជាប់មនុស្សទៅកាន់គោលដៅរបស់ពួកគេជាមួយនឹងការយកចិត្តទុកដាក់លើភាពទាន់ពេលវេលា សុវត្ថិភាព និងការពេញចិត្តរបស់អតិថិជន។',
    missionStatementPart2: 'យើងជឿថាការធ្វើដំណើរគួរតែគ្មានភាពតានតឹង និងរីករាយ។ នោះហើយជាមូលហេតុដែលយើងរក្សាស្តង់ដារខ្ពស់បំផុតក្នុងការថែទាំយានយន្ត ការបណ្តុះបណ្តាលអ្នកបើកបរ និងសេវាកម្មអតិថិជនដើម្បីធានាថាគ្រប់ការធ្វើដំណើរជាមួយយើងគឺជាបទពិសោធន៍វិជ្ជមាន។',
    ourAchievements: 'សមិទ្ធិផលរបស់យើង',
    happyCustomers: 'អតិថិជនរីករាយ',
    yearsExperience: 'ឆ្នាំបទពិសោធន៍',
    routesCovered: 'ផ្លូវគ្របដណ្តប់',
    onTimeArrival: 'មកដល់ទាន់ពេលវេលា',
    linterWarnings: 'Linter warnings and errors.',
    ourVehicleFleet: 'កងយានយន្តរបស់យើង',
    standardBus: 'ឡានក្រុងស្តង់ដារ',
    capacity: 'សមត្ថភាព',
    passengersShort: 'អ្នកដំណើរ',
    airConditioning: 'ម៉ាស៊ីនត្រជាក់',
    comfortableSeats: 'កៅអីផាសុកភាព',
    storageSpace: 'កន្លែងផ្ទុកអីវ៉ាន់',
    vipBus: 'ឡានក្រុង VIP',
    recliningSeats: 'កៅអីអាចដាក់បាន',
    extraLegroom: 'កន្លែងដាក់ជើងបន្ថែម',
    entertainmentSystem: 'ប្រព័ន្ធកម្សាន្ត',
    miniVan: 'រថយន្តតូច',
    privateTransport: 'ការដឹកជញ្ជូនឯកជន',
    flexibleSchedule: 'កាលវិភាគបត់បែន',
    doorToDoorService: 'សេវាកម្មដឹកជញ្ជូនដល់ផ្ទះ',
    safetyStandards: 'ស្តង់ដារសុវត្ថិភាព',
    yourSafetyPriority: 'សុវត្ថិភាពរបស់អ្នកគឺជាអាទិភាពចម្បងរបស់យើង។ យើងរក្សាស្តង់ដារសុវត្ថិភាពខ្ពស់បំផុតក្នុងគ្រប់អ្វីដែលយើងធ្វើ។',
    vehicleSafety: 'សុវត្ថិភាពយានយន្ត',
    regularVehicleMaintenance: 'ការថែទាំនិងត្រួតពិនិត្យយានយន្តជាទៀងទាត់',
    modernSafetyEquipment: 'ឧបករណ៍សុវត្ថិភាពទំនើបនិងផ្លូវចេញបន្ទាន់',
    gpsTracking: 'ប្រព័ន្ធតាមដាន GPS និងប្រព័ន្ធទំនាក់ទំនង',
    firstAidKits: 'ឧបករណ៍ជំនួយដំបូងនិងឧបករណ៍សុវត្ថិភាពនៅលើយន្តហោះ',
    driverTraining: 'ការបណ្តុះបណ្តាលអ្នកបើកបរ',
    professionalDriverCertification: 'វិញ្ញាបនបត្រនិងការបណ្តុះបណ្តាលអ្នកបើកបរបែបអាជីព',
    regularSafetyTraining: 'ការបណ្តុះបណ្តាលសុវត្ថិភាពនិងសេវាកម្មអតិថិជនជាទៀងទាត់',
    backgroundChecks: 'ការត្រួតពិនិត្យប្រវត្តិរូបនិងការពិនិត្យសុខភាព',
    continuousMonitoring: 'ការត្រួតពិនិត្យនិងការវាយតម្លៃលទ្ធផលជាបន្តបន្ទាប់',
    // Booking Confirmation Page
    noBookingDataFound: 'មិនមានទិន្នន័យកក់ទេ',
    makeABooking: 'ធ្វើការកក់',
    bookingConfirmed: 'ការកក់បានបញ្ជាក់!',
    bookingSuccessfullySubmitted: 'ការកក់របស់អ្នកត្រូវបានដាក់ស្នើដោយជោគជ័យ',
    bookingID: 'លេខកក់:',
    tripInformation: 'ព័ត៌មានធ្វើដំណើរ',
    route: 'ផ្លូវ',
    departureDate: 'ថ្ងៃចេញដំណើរ',
    totalPassengers: 'ចំនួនអ្នកដំណើរសរុប',
    passengerDetails: 'ព័ត៌មានលម្អិតអ្នកដំណើរ',
    primaryPassenger: 'Primary Passenger',
    importantInformation: 'ព័ត៌មានសំខាន់',
    arriveEarly: 'Please arrive at the departure location 30 minutes before scheduled time',
    validID: 'Bring a valid ID for verification',
    contactForChanges: 'Contact us at +855 69 373 415 if you need to make changes',
    confirmationEmailSent: 'A confirmation email will be sent to',
    backToHome: 'ត្រឡប់ទៅទំព័រដើមវិញ',
    makeAnotherBooking: 'ធ្វើការកក់មួយទៀត',
    dateNotSelected: 'កាលបរិច្ឆេទមិនត្រូវបានជ្រើសរើស',
    notFound_oops: "អុញអ្ហា៎! រកទំព័រមិនឃើញ",
    notFound_returnHome: "ត្រឡប់ទៅទំព័រដើមវិញ",
    availableTrips: "ជើងធ្វើដំណើរដែលមាន",
    arrivalTime: "ម៉ោងមកដល់",
    vanType: "ប្រភេទឡាន",
    findTrips: "ស្វែងរកជើងធ្វើដំណើរ",
    viewBookingHistory: 'ការកក់របស់ខ្ញុំ',
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<string>(() => {
    return localStorage.getItem('language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string, replacements?: Record<string, string | number>) => {
    let translation = translations[language][key];
    if (translation === undefined) {
      console.warn(`Translation for key "${key}" not found in language "${language}"`);
      return key; // Fallback to key if translation not found
    }

    if (replacements) {
      for (const [placeholder, value] of Object.entries(replacements)) {
        translation = translation.replace(new RegExp(`\{${placeholder}\}`, 'g'), String(value));
      }
    }
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};